name: deploy
on: push
jobs:
  deploy:
    name: build image
    runs-on: ubuntu-latest
    env:
      GITHUB_WORKSPACE: /workdir
    container:
      image: rafa606/vim-with-latex
      volumes:
        - ${{ github.workspace }}:/workdir
    steps:
      - name: checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v17.2
        with:
          files: |
            src/*.tex

      - name: Build pdf and push
        run: |
          apt-get install lmodern
          cd src
          pdflatex 00_curriculum.tex
          pdflatex 00_curriculum.tex
          pdflatex 00_curriculum.tex
        if: steps.changed-files-specific.outputs.any_changed == 'true'
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') &&
            steps.changed-files-specific.outputs.any_changed == 'true'
        with:
          files: src/00_currisulum.pdf
